POST https://estudos-node.onrender.com/cars
Content-Type: application/json

{
    "title": "Car ford",
    "description": "car is for sale",
    "mileage": "100000"
}


###

GET https://estudos-node.onrender.com/cars


### 
PUT https://estudos-node.onrender.com/cars/1a1a8c43-eb4d-4074-acd1-b0c17b13fede
Content-Type: application/json

{
    "title": "Car 01",
    "description": "car saled",
    "mileage": "100000"
}
 

### 
DELETE https://estudos-node.onrender.com/cars/1a1a8c43-eb4d-4074-acd1-b0c17b13fede